apiVersion: apps/v1
kind: Deployment
metadata:
  name: builder-dind-deployment
  labels:
    app: builder-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builder-dind
  template:
    metadata:
      labels:
        app: builder-dind
    spec:
      volumes:
      - name: dockerfile-volume
        configMap:
          name: dockerfile-configmap
      containers:
      - name: builder-dind
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: dockerfile-volume
          mountPath: /dockerfile
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "250m"