apiVersion: batch/v1
kind: Job
metadata:
  name: job-builder-kaniko
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: builder-kaniko
    spec:
      restartPolicy: Never
      volumes:
      - name: dockerfile-volume
        configMap:
          name: dockerfile-configmap
      - name: credentials-volume
        configMap:
          name: credentials-configmap
      containers:
      - name: builder-kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/dockerfile/Dockerfile"
        - "--context=dir:///workspace"
        - "--destination=i999999.artifact-registry.corvina.cloud/4a19535f-0eb7-4953-a058-585490337ff9_100/hello-kaniko:latest"
        # command: ["/kaniko/executor"]
        volumeMounts:
        - name: dockerfile-volume
          mountPath: /dockerfile
        - name: credentials-volume
          mountPath: /kaniko/.docker
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "250m"
