apiVersion: batch/v1
kind: Job
metadata:
  name: job-builder-kaniko
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: builder-kaniko
    spec:
      restartPolicy: Never
      volumes:
      - name: dockerfile-volume
        configMap:
          name: dockerfile-configmap
      containers:
      - name: builder-kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/dockerfile/Dockerfile"
        - "--context=dir:///workspace"
        - "--no-push"
        - "--destination=kaniko-image:latest"
        # command: ["/kaniko/executor"]
        volumeMounts:
        - name: dockerfile-volume
          mountPath: /dockerfile
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "250m"
